# Generated by Django 4.1.6 on 2023-02-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('subject', 'teacher_id', 'date', 'start_time'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('subject', 'teacher_id'), 'verbose_name': 'Материал к уроку', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('title',), 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
