version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
       - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  web:
    build:
      context: ../
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: always
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.20
    volumes:
       - pgadmin:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: unless-stopped

  redis:
    image: redis:7-alpine3.17
    container_name: redis
    restart: always
    volumes:
      - redis:/data

  celery:
    build:
      context: ../
    container_name: celery
    depends_on:
      - web
    restart:
      always
    command: celery -A core worker -l INFO

# networks:
#  postgres:
#    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis: